---

- name: ensure tasks run only on selected os releases
  block:

    - name: install powerline
      ansible.builtin.package:
        name: "{{ powerline_packages_base | ansible.builtin.union(powerline_packages_arch) }}"
      when:
        - ansible_distribution == "Archlinux"
        - ansible_distribution_release == "holo"

    - name: install powerline
      ansible.builtin.package:
        name: "{{ powerline_packages_base | ansible.builtin.union(powerline_packages_redhat) }}"
      when: ansible_distribution == "Fedora"

    - name: locate powerline-bash script
      ansible.builtin.shell:
        cmd: find / -name powerline.sh | grep -i bash
      changed_when: false
      register: bash_powerline

    - name: display powerline location
      ansible.builtin.debug:
        var: bash_powerline
        verbosity: 1

    - name: configure powerline for bash
      ansible.builtin.template:
        src: powerline_bash.sh.j2
        dest: /etc/profile.d/powerline-bash.sh
        owner: root
        group: root
        mode: "0644"

    - name: configure powerline for tmux
      ansible.builtin.template:
        src: powerline_tmux.sh.j2
        dest: /etc/profile.d/powerline-tmux.sh
        owner: root
        group: root
        mode: "0644"

    - name: initialize vimrc generator
      ansible.builtin.include_role:
        name: text_editor
        tasks_from: vimrc_template.yml

    - name: add powerline variable(s) to vimrc generator
      ansible.builtin.include_role:
        name: text_editor
        tasks_from: vimrc_injector.yml
      vars:
        vimrc_label: powerline
        vimrc_type: variable
        vimrc_content: "{{ powerline_vimrc_variables }}"

    - name: add powerline script(s) to vimrc generator
      ansible.builtin.include_role:
        name: text_editor
        tasks_from: vimrc_injector.yml
      vars:
        vimrc_label: powerline
        vimrc_type: script
        vimrc_content: "{{ powerline_vimrc_scripts }}"

    - name: disable steamdeck prompt
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '^PROMPT_COMMAND='
        replace: '#PROMPT_COMMAND='
      loop:
        - /etc/bash.bashrc
        - /home/deck/.bashrc
      when:
        - ansible_distribution == "Archlinux"
        - ansible_distribution_release == "holo"

  when: >
    (ansible_distribution == "Archlinux" and ansible_distribution_release == "holo") or
    ansible_distribution == "Fedora"

...
